// **************************************************
// Custom code for UD100Form
// Created: 7/18/2013 4:12:46 PM
// **************************************************
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Windows.Forms;
using Epicor.Mfg.BO;
using Epicor.Mfg.Core;
using Epicor.Mfg.Lib;
using Epicor.Mfg.UI;
using Epicor.Mfg.UI.Adapters;
using Epicor.Mfg.UI.Customization;
using Epicor.Mfg.UI.ExtendedProps;
using Epicor.Mfg.UI.FormFunctions;
using Epicor.Mfg.UI.FrameWork;
using Epicor.Mfg.UI.Searches;
using Infragistics.Win.UltraWinToolbars;
using Infragistics.Win.UltraWinGrid;
using System.Net.Mail;
using System.Reflection;

public class Script
{
    // ** Wizard Insert Location - Do Not Remove 'Begin/End Wizard Added Module Level Variables' Comments! **
    // Begin Wizard Added Module Level Variables **
    private EpiDataView edvUD100;
    private EpiBaseAdapter oTrans_adapter;
	private EpiDataView edvUD100A;
    // End Wizard Added Module Level Variables **

    // Add Custom Module Level Variables Here **
    private List<string> selUsers = new List<string>();
    private List<string> affectedWOs = new List<string>();
    private List<string> disposition = new List<string>();
    private static ButtonTool btnPrintReport;

    public void InitializeCustomCode() {
        // ** Wizard Insert Location - Do not delete 'Begin/End Wizard Added Variable Initialization' lines **
        // Begin Wizard Added Variable Initialization

        edvUD100 = ((EpiDataView)(oTrans.EpiDataViews["UD100"]));
        edvUD100.EpiViewNotification += edvUD100_EpiViewNotification;
        UD100_Column.ColumnChanged += UD100_AfterFieldChange;
        UD100_Column.ColumnChanging += UD100_BeforeFieldChange;
        this.oTrans_adapter = ((EpiBaseAdapter)(this.csm.TransAdaptersHT["oTrans_adapter"]));
        // this.oTrans_adapter.BeforeAdapterMethod += new BeforeAdapterMethod(this.oTrans_adapter_BeforeAdapterMethod);
		this.edvUD100A = ((EpiDataView)(this.oTrans.EpiDataViews["UD100A"]));
		this.edvUD100A.EpiViewNotification += new EpiViewNotification(this.edvUD100A_EpiViewNotification);
        // End Wizard Added Variable Initialization

        // Begin Wizard Added Custom Method Calls
        btnSelectUser.Click += btnSelectUser_Click;
        btnRemoveUser.Click += btnRemoveUser_Click;
        CreateRowRuleUD100ACheckBox01Equals_FALSE();
        CreateRowRuleUD100ACheckBox02Equals_FALSE();
        btnRollup.Click += btnRollup_Click;
        btnFetchAll.Click += btnFetchAll_Click;
        btnRequest.Click += btnRequest_Click;
        SetExtendedProperties();
        // End Wizard Added Custom Method Calls
        epiButtonC1.Click += epiButtonC1_Click;
        btnPartNumber.Click += btnPartNumber_Click;
        EpiTextBox key1TextBox = (EpiTextBox)csm.GetNativeControlReference("46567b2e-6bc0-4967-be35-a0ec6843838f");
        key1TextBox.Leave += key1TextBox_Leave;
    }

    public void DestroyCustomCode() {
        // ** Wizard Insert Location - Do not delete 'Begin/End Wizard Added Object Disposal' lines **
        // Begin Wizard Added Object Disposal

        edvUD100.EpiViewNotification -= edvUD100_EpiViewNotification;
        edvUD100 = null;
        btnSelectUser.Click -= btnSelectUser_Click;
        btnRemoveUser.Click -= btnRemoveUser_Click;
        btnRollup.Click -= btnRollup_Click;
        UD100_Column.ColumnChanged -= UD100_AfterFieldChange;
        btnFetchAll.Click -= btnFetchAll_Click;
        btnRequest.Click -= btnRequest_Click;
        UD100_Column.ColumnChanging -= UD100_BeforeFieldChange;
        //this.oTrans_adapter.BeforeAdapterMethod -= new BeforeAdapterMethod(this.oTrans_adapter_BeforeAdapterMethod);
        this.oTrans_adapter = null;
		this.edvUD100A.EpiViewNotification -= new EpiViewNotification(this.edvUD100A_EpiViewNotification);
		this.edvUD100A = null;
        // End Wizard Added Object Disposal

        // Begin Custom Code Disposal

        // End Custom Code Disposal
        epiButtonC1.Click -= epiButtonC1_Click;
        btnPartNumber.Click -= btnPartNumber_Click;
        EpiTextBox key1TextBox = (EpiTextBox)csm.GetNativeControlReference("46567b2e-6bc0-4967-be35-a0ec6843838f");
        key1TextBox.Leave -= key1TextBox_Leave;
    }

    private void CreateRowRuleUD100ACheckBox01Equals_FALSE() {
        // Description: BOM REQ
        // **** begin autogenerated code ****
        RuleAction invisibleUD100A_Date01 = RuleAction.AddControlSettings(oTrans, "UD100A.Date01", SettingStyle.Invisible);
        RuleAction[] ruleActions = {invisibleUD100A_Date01};
        // Create RowRule and add to the EpiDataView.
        RowRule rrCreateRowRuleUD100ACheckBox01Equals_FALSE = new RowRule("UD100A.CheckBox01", RuleCondition.Equals, false, ruleActions);
        ((EpiDataView)(oTrans.EpiDataViews["UD100A"])).AddRowRule(rrCreateRowRuleUD100ACheckBox01Equals_FALSE);
        // **** end autogenerated code ****
    }

    private void CreateRowRuleUD100ACheckBox02Equals_FALSE() {
        // Description: Lable REQ
        // **** begin autogenerated code ****
        RuleAction invisibleUD100A_Date02 = RuleAction.AddControlSettings(oTrans, "UD100A.Date02", SettingStyle.Invisible);
        RuleAction[] ruleActions = {invisibleUD100A_Date02};
        // Create RowRule and add to the EpiDataView.
        RowRule rrCreateRowRuleUD100ACheckBox02Equals_FALSE = new RowRule("UD100A.CheckBox02", RuleCondition.Equals, false, ruleActions);
        ((EpiDataView)(oTrans.EpiDataViews["UD100A"])).AddRowRule(rrCreateRowRuleUD100ACheckBox02Equals_FALSE);
        // **** end autogenerated code ****
    }

    private void SetExtendedProperties() {
//        edvUD100.dataView.Table.Columns["Character03"].ExtendedProperties["ReadOnly"] = true;
//        edvUD100.dataView.Table.Columns["Character05"].ExtendedProperties["ReadOnly"] = true;
//        edvUD100.dataView.Table.Columns["Character06"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Appr_CTNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Appr_MXNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Appr_TXNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Appr_UKNotes"].ExtendedProperties["ReadOnly"] = true;
		edvUD100.dataView.Table.Columns["Appr_PLNotes"].ExtendedProperties["ReadOnly"] = true; //added by scott
		edvUD100.dataView.Table.Columns["CertificationAckNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["CertificationAppNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["ContractsAckNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["ContractsAppNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["DesignEngAckNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["DesignEngAppNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["MangEngAckNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["MangEngAppNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["AS9100_AckNotes"].ExtendedProperties["ReadOnly"] = true; //added by scott
        edvUD100.dataView.Table.Columns["AS9100AppNotes"].ExtendedProperties["ReadOnly"] = true; // added by scott
        edvUD100.dataView.Table.Columns["SCM_AckNotes"].ExtendedProperties["ReadOnly"] = true; //added by scott
        edvUD100.dataView.Table.Columns["SCM_AppNotes"].ExtendedProperties["ReadOnly"] = true; // added by scott
		edvUD100.dataView.Table.Columns["SCM_2_AckNotes"].ExtendedProperties["ReadOnly"] = true; //added by scott
        edvUD100.dataView.Table.Columns["SCM_2_AppNotes"].ExtendedProperties["ReadOnly"] = true; // added by scott
		//edvUD100.dataView.Table.Columns["SCM_ProdPlant"].ExtendedProperties["ReadOnly"] = true; // added by scott
        edvUD100.dataView.Table.Columns["ProductionControlAckNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["ProductionControlAppNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["QualityAckNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["QualityAppNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_BOMNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_CertificationNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_CustomerApproval"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_CustomerSourceNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_DispositionNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_DrawingNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_FAINotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_GPDNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_InterPlantNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_LabelNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_PatternNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_PricingNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_RawMaterialNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_ToolingNotes"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_PartDesc"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_SubmitToCust"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_GerberReady"].ExtendedProperties["ReadOnly"] = true;
        edvUD100.dataView.Table.Columns["Tasks_GerberRelease"].ExtendedProperties["ReadOnly"] = true;
		edvUD100.dataView.Table.Columns["SCD_ENG_TSK"].ExtendedProperties["ReadOnly"] = true;
		
    }

    private void UD100Form_Load(object sender, EventArgs args) {
        //  Setup report button
        if (UD100Form.MainToolManager == null || UD100Form.MainToolManager.Tools.Exists("PrintReport"))
            return;

        PopupMenuTool actionsMenu = (PopupMenuTool)UD100Form.MainToolManager.Tools["ActionsMenu"];
        btnPrintReport = new ButtonTool("PrintReport");
        btnPrintReport.CustomizedCaption = "Print Report";

        btnPrintReport.ToolClick += btnPrintReport_Click;

        UD100Form.MainToolManager.Tools.Add(btnPrintReport);
        actionsMenu.Tools.Add(btnPrintReport);

        // Change new record button captions.
        UD100Form.MainToolManager.Tools["EpiAddNewnewChild"].SharedProps.CustomizerCaption = "New Part";
        UD100Form.MainToolManager.Tools["EpiAddNewnewChild"].SharedProps.Caption = "New Part";
        UD100Form.MainToolManager.Tools["EpiAddNewnewParent"].SharedProps.CustomizerCaption = "New ECR";
        UD100Form.MainToolManager.Tools["EpiAddNewnewParent"].SharedProps.Caption = "New ECR";
    }

    private void UD100_BeforeFieldChange(object sender, DataColumnChangeEventArgs args) {
oTrans.PushStatusText("UD100_BeforeFieldChange", false);
        // ** Argument Properties and Uses **
        // args.Row["FieldName"]
        // args.Column, args.ProposedValue, args.Row
        // Add Event Handler Code
        switch (args.Column.ColumnName) {
            case "CertificationAckCheckbox":
            case "ContractsAckCheckbox":
            case "DesignEngAckCheckbox":
            case "MangEngAckCheckbox":
            case "ProductionControlAckCheckbox":
            case "QualityAckCheckbox":
            case "AS9100_AckCheckBox": //added by scott
			case "SCM_AckCheckbox": //added by scott
			case "SCM_2_AckCheckbox": //added by scott
			
			    if (Convert.ToBoolean(args.ProposedValue) == false)
                    args.ProposedValue = true;
                break;
        }
oTrans.PushStatusText("UD100_BeforeFieldChange end", false);
    }

    private void UD100_AfterFieldChange(object sender, DataColumnChangeEventArgs args) {
oTrans.PushStatusText("UD100_AfterFieldChange", false);
        // ** Argument Properties and Uses **
        // args.Row["FieldName"]
        // args.Column, args.ProposedValue, args.Row
        // Add Event Handler Code
        switch (args.Column.ColumnName) {
            case "ShortChar02":
                SendStatusAlerts(args.ProposedValue.ToString(), args.Row["Key1"].ToString());
                break;
            case "CertificationAckCheckbox":
            case "ContractsAckCheckbox":
            case "DesignEngAckCheckbox":
            case "MangEngAckCheckbox":
            case "ProductionControlAckCheckbox":
            case "QualityAckCheckbox":
            case "AS9100_AckCheckBox": //added by scott
			case "SCM_AckCheckbox": //added by Scott
			case "SCM_2_AckCheckbox": //added by Scott
			
            case "CheckBox01":
            case "CheckBox02":
            case "CheckBox03":
            case "CheckBox04":
            case "CheckBox05":
            case "CheckBox06":
            case "CheckBox07":
            case "CheckBox08":
            case "CheckBox09":
            case "CheckBox10":
            case "CheckBox11":
            case "CheckBox12":
            case "CheckBox13":
            case "CheckBox14":
            // case "CheckBox15":
            case "CheckBox16":
            case "CheckBox17":
            case "CheckBox18":
            case "CheckBox19":
            case "CheckBox20":
			case "Tasks_PartDescBOOL":
			case "Tasks_SubmitBOOL":
			case "Tasks_GerberReadyBool":
			case "Tasks_GerberReleaseBool":
			case "SCD_ENG_YN": 
                SetCheckBoxNotes(args);
                break;
            case "CertificationAppCheckbox":
            case "ContractsAppCheckbox":
            case "DesignEngAppCheckbox":
            case "MangEngAppCheckbox":
            case "ProductionControlAppCheckbox":
            case "AS9100_AppCheckBox": //added by scott
            case "QualityAppCheckbox":
			case "SCM_AppCheckbox":
			case "SCM_2_AppCheckbox":
oTrans.PushStatusText("SCM_2_AppCheckbox", false);
			    if (Convert.ToBoolean(args.ProposedValue) != IsAcknowledged(args)) {
oTrans.PushStatusText("SCM_2_AppCheckbox 1", false);
                    args.Row[args.Column.ColumnName] = IsAcknowledged(args);
oTrans.PushStatusText("SCM_2_AppCheckbox 2", false);
                    args.ProposedValue = args.Row[args.Column.ColumnName];
                }
oTrans.PushStatusText("SCM_2_AppCheckbox 3", false);
                SetCheckBoxNotes(args);
                break;
            case "Character02":
                AddTeamEmailsToSelectedUsers();
                break;
        }
oTrans.PushStatusText("UD100_AfterFieldChange end", false);
    }

    private void AddTeamEmailsToSelectedUsers() {
oTrans.PushStatusText("AddTeamEmailsToSelectedUsers", false);
        string Team = edvUD100.dataView[edvUD100.Row]["Character02"].ToString();
        string TeamID = string.Empty;
        switch (Team) {
            case "Team Black": {
                TeamID = "TM_Black";
            }
                break;
            case "Team Blue": {
                TeamID = "TM_Blue";
            }
                break;
            case "Team Flex": {
                TeamID = "TM_Flex";
            }
                break;
            case "Team Green": {
                TeamID = "TM_Green";
            }
                break;
            case "Team Red": {
                TeamID = "TM_Red";
            }
                break;
            case "Team TCI": {
                TeamID = "TM_CI";
            }
                break;
			case "Team Yellow": {
                TeamID = "TM_Yello";
            }
                break;
            case "Team R&D": {
                TeamID = "TM_RD";
            }
                break;
            case "Team UK": {
                TeamID = "TM_UK";
            }
                break;
        }

        foreach (UltraGridRow row in eugAllUsers.Selected.Rows)
            selUsers.Add(row.Cells[0].Value.ToString());

        DataTable userFileRows = GetUserFileRows();

        List<string> addresses = new List<string>();
        foreach (DataRow row in userFileRows.Rows) {
            string emailAddress = row[0].ToString();
            string username = row[1].ToString();
            string groupList = row[2].ToString();
            if (!string.IsNullOrEmpty(username) && groupList.Contains(TeamID) && !selUsers.Contains(username))
                selUsers.Add(username);
        }

        eugSelectedUsers.DataSource = selUsers;

        String catUsers = "";
        foreach (String user in selUsers)
            if (user.Length > 0)
                catUsers += user + "~";

        edvUD100.dataView[edvUD100.Row]["Character04"] = catUsers;
oTrans.PushStatusText("AddTeamEmailsToSelectedUsers END", false);
    }

    private bool IsUserECRAdmin(string maybeAdminID) {
oTrans.PushStatusText("IsUserECRAdmin", false);
        DataTable userFileRows = GetUserFileRows();

	    //foreach (DataColumn dataColumn in userFileRows.Columns) {
        //    MessageBox.Show(dataColumn.ColumnName);
        //}

        foreach (DataRow row in userFileRows.Rows) {
            string userID = row["UserFile.DcdUserID"].ToString();
            string groupList = row["UserFile.GroupList"].ToString();
            if (userID == maybeAdminID && groupList.Contains("ECR1"))
                return true;
        }
oTrans.PushStatusText("IsUserECRAdmin END", false);
        return false;
    }

    private void edvUD100_EpiViewNotification(EpiDataView view, EpiNotifyArgs args) {
oTrans.PushStatusText("edvUD100_EpiViewNotification", false);
        // ** Argument Properties and Uses **
        // view.dataView[args.Row]["FieldName"]
        // args.Row, args.Column, args.Sender, args.NotifyType
        // NotifyType.Initialize, NotifyType.AddRow, NotifyType.DeleteRow, NotifyType.InitLastView, NotifyType.InitAndResetTreeNodes				
        if ((args.Row > -1)) {
            //  Apply field security
oTrans.PushStatusText("1", false);
            bool isStatusNull = string.IsNullOrEmpty(view.dataView[view.Row]["ShortChar02"].ToString());
            string userID = ((Session)oTrans.Session).UserID;
            bool isUserAdmin = IsUserECRAdmin(userID);

            if (isStatusNull && !isUserAdmin)
                //EpiMessageBox.Show("Opening Some Fields");
                OpenSomeFields();
            else if (isUserAdmin)
                //EpiMessageBox.Show("Opening ALL Fields");
                OpenAllFields(true);
            else
                //EpiMessageBox.Show("Opening NO Fields");
                OpenAllFields(false);
            //  User grid
oTrans.PushStatusText("2", false);
            if (eugAllUsers.Rows.Count < 1) {
                DynamicQuery dq = new DynamicQuery(((Session)oTrans.Session).ConnectionPool);
                DataSet ds = dq.ExecuteByID("CIC68322-UserLookup");

                if (ds.Tables[0].Rows.Count < 1)
                    return;

                eugAllUsers.DataSource = ds.Tables[0];
            }

            String catUsers = view.dataView[args.Row]["Character04"].ToString();
            selUsers = new List<string>();
            foreach (string s in catUsers.Split('~'))
                if (s.Length > 0)
                    selUsers.Add(s);

            eugSelectedUsers.DataSource = selUsers;

//WHERE USED
			DataTable whereused = new DataTable();
			whereused.Columns.Add("Company", typeof(string));
			whereused.Columns.Add("PartNum", typeof(string));
			if((string)view.dataView[args.Row]["Character06"] != string.Empty)
			{
				foreach(string lines in ((string)view.dataView[args.Row]["Character06"]).Split(new string[]{Environment.NewLine}, StringSplitOptions.None))
				{
					string[] columns = lines.Split(new string[]{" - "}, StringSplitOptions.None);
					DataRow r = whereused.NewRow();
					if(columns.Length < 2){
						r["Company"] = string.Empty;
						r["PartNum"] = columns[0].Trim();
					}
					else{
						r["Company"] = columns[0].Trim();
						r["PartNum"] = columns[1].Trim();
					}
					whereused.Rows.Add(r);
				}
			}
			epiUltraGridC1_WhereUsed.DataSource = whereused;

//JOBS
			DataTable jobs = new DataTable();
			jobs.Columns.Add("Company", typeof(string));
			jobs.Columns.Add("JobNum", typeof(string));
			jobs.Columns.Add("StartDate", typeof(DateTime));
			jobs.Columns.Add("Qty", typeof(int));
			if((string)view.dataView[args.Row]["Character03"]!=string.Empty)
			{
				foreach(string lines in ((string)view.dataView[args.Row]["Character03"]).Split(new string[]{Environment.NewLine}, StringSplitOptions.None))
				{
					string[] columns = lines.Split(new string[]{" - "}, StringSplitOptions.None);
					DataRow r = jobs.NewRow();
					if(columns.Length < 4){
						r["Company"] = string.Empty;
						r["JobNum"] = columns[0].Trim();
						r["StartDate"] = Convert.ToDateTime(columns[1].Trim());
						r["Qty"] = Convert.ToInt32(columns[2].Trim());
					}
					else{
						r["Company"] = columns[0].Trim();
						r["JobNum"] = columns[1].Trim();
						r["StartDate"] = Convert.ToDateTime(columns[2].Trim());
						r["Qty"] = Convert.ToInt32(columns[3].Trim());
					}
					jobs.Rows.Add(r);
				}
			}
			epiUltraGridC1_AffectedWorkorders.DataSource = jobs;

//Disposition
			DataTable disposition = new DataTable();
			disposition.Columns.Add("Company", typeof(string));
			disposition.Columns.Add("PartNum", typeof(string));
			disposition.Columns.Add("Warehouse", typeof(string));
			disposition.Columns.Add("On Hand Qty", typeof(decimal));
			disposition.Columns.Add("Plant", typeof(string));

oTrans.PushStatusText("5", false);
			if((string)view.dataView[args.Row]["Character05"]!=string.Empty)
			{
				foreach(string lines in ((string)view.dataView[args.Row]["Character05"]).Split(new string[]{Environment.NewLine}, StringSplitOptions.None))
				{
					string[] columns = lines.Split(new string[]{" - "}, StringSplitOptions.None);
					DataRow r = disposition.NewRow();
					if(columns.Length < 5){
						r["Company"] = string.Empty;
						r["PartNum"] = columns[0].Trim();
						r["warehouse"] = columns[1].Trim();
						r["On Hand Qty"] = Convert.ToDecimal(columns[2].Trim());
						r["Plant"] = columns[3].Trim();
					}else{
						r["Company"] = columns[0].Trim();
						r["PartNum"] = columns[1].Trim();
						r["warehouse"] = columns[2].Trim();
						r["On Hand Qty"] = Convert.ToDecimal(columns[3].Trim());
						r["Plant"] = columns[4].Trim();
					}
					disposition.Rows.Add(r);
				}
			}
			epiUltraGridC1_DispositionInfo.DataSource = disposition;

        }

        if ((args.Row < 0)) {
            selUsers = new List<string>();
            eugSelectedUsers.DataSource = selUsers;
            eugAllUsers.DataSource = null;
        }
oTrans.PushStatusText("edvUD100_EpiViewNotification END", false);
    }

    private void OpenSomeFields() {
oTrans.PushStatusText("OpenSomeFields", false);
        bool isProtected = true;
        bool isEnabled = true;
        //bool IsStatusNull = !Protected;

        // ShortChar## are #*%!ing stupid and need ot use the native controll to do this.  
        csm.GetNativeControlReference("c8ce8aa7-2d99-4e26-b62b-b87dab0aa08f").Enabled = !isProtected; //cmdStatus
        csm.GetNativeControlReference("708d7b91-54e1-4e71-bba7-455a507277a5").Enabled = isProtected; //cmdECRClass
        csm.GetNativeControlReference("e8bd03e1-15bb-44b8-b305-2d2353d6f1d0").Enabled = isProtected; //cmdReasonCode
        csm.GetNativeControlReference("bd77eb04-31eb-4a97-ad52-f568c6c4364c").Enabled = isProtected; //txtDWGCurrent
        csm.GetNativeControlReference("88bab32e-5196-4071-b186-44dea5e0c008").Enabled = isProtected; //txtDWGNew
        csm.GetNativeControlReference("fd00583e-a569-4bd3-8bde-8aafefc73ad4").Enabled = isProtected; //txtGPDCurrent
        csm.GetNativeControlReference("dcd2158b-c50a-4499-96dc-213b7a2b0528").Enabled = isProtected; //txtGPDNew
        csm.GetNativeControlReference("03cd1d10-4269-463d-80c2-dfef25caff94").Enabled = isProtected; //txtGerberCurrent
        csm.GetNativeControlReference("109f5c69-e2e3-41d6-96b5-65d686844290").Enabled = isProtected; //txtGerberNew
        txtRequester.ReadOnly = isProtected;
        dteRequestDate.ReadOnly = !isEnabled;
        dteGerberRelease.ReadOnly = isEnabled;
        cmbTeam.ReadOnly = !isProtected;
        txtDMRNum.ReadOnly = !isProtected;
        txtProject.ReadOnly = !isProtected;
        dteOpen.ReadOnly = isProtected;
        dteDue.ReadOnly = !isProtected;
        dteClosed.ReadOnly = isProtected;
        dteOnHold.ReadOnly = isProtected;
        dteOffHold.ReadOnly = isProtected;
        dteWorkAreaRelease.ReadOnly = isProtected;
        dteGerberRelease.ReadOnly = isProtected;
        dteGerberRelease.ReadOnly = isProtected;
        chkLBLRequired.ReadOnly = isProtected;
        chkBOMRequired.ReadOnly = isProtected;
        btnRequest.Enabled = isEnabled;
        //epiCheckBoxC22.Enabled = !isEnabled;
        // desc
        csm.GetNativeControlReference("368fd000-b055-4183-9d70-25d986650bd9").Enabled = true;
        // part tab
        btnPartNumber.Enabled = isProtected;
        //txtPartDesc.Enabled = isProtected;
        csm.GetNativeControlReference("9ba33a90-56ec-4084-ae5d-f1f45a050f92").Enabled = isProtected;
oTrans.PushStatusText("OpenSomeFields END", false);
    }

    private void OpenAllFields(bool IsStatusNull) {
oTrans.PushStatusText("OpenAllFields", false);
        bool Protected = !IsStatusNull;
        // ShortChar## are #*%!ing stupid and need ot use the native controll to do this.  
        csm.GetNativeControlReference("c8ce8aa7-2d99-4e26-b62b-b87dab0aa08f").Enabled = !Protected; //cmdStatus
        csm.GetNativeControlReference("708d7b91-54e1-4e71-bba7-455a507277a5").Enabled = !Protected; //cmdECRClass
        csm.GetNativeControlReference("e8bd03e1-15bb-44b8-b305-2d2353d6f1d0").Enabled = !Protected; //cmdReasonCode
        csm.GetNativeControlReference("bd77eb04-31eb-4a97-ad52-f568c6c4364c").Enabled = !Protected; //txtDWGCurrent
        csm.GetNativeControlReference("88bab32e-5196-4071-b186-44dea5e0c008").Enabled = !Protected; //txtDWGNew
        csm.GetNativeControlReference("fd00583e-a569-4bd3-8bde-8aafefc73ad4").Enabled = !Protected; //txtGPDCurrent
        csm.GetNativeControlReference("dcd2158b-c50a-4499-96dc-213b7a2b0528").Enabled = !Protected; //txtGPDNew
        csm.GetNativeControlReference("03cd1d10-4269-463d-80c2-dfef25caff94").Enabled = !Protected; //txtGerberCurrent
        csm.GetNativeControlReference("109f5c69-e2e3-41d6-96b5-65d686844290").Enabled = !Protected; //txtGerberNew
        edvUD100.dataView.Table.Columns["Date01"].ExtendedProperties["ReadOnly"] = true;
        epiButtonC1.ReadOnly = Protected;
        txtRequester.ReadOnly = Protected;
        dteRequestDate.ReadOnly = Protected;
        cmbTeam.ReadOnly = Protected;
        cmbReasonCode.ReadOnly = Protected;
        txtDMRNum.ReadOnly = Protected;
        txtProject.ReadOnly = Protected;
        dteOpen.ReadOnly = Protected;
        dteClosed.ReadOnly = Protected;
        dteOnHold.ReadOnly = Protected;
        dteOffHold.ReadOnly = Protected;
        dteWorkAreaRelease.ReadOnly = Protected;
        dteGerberRelease.ReadOnly = Protected;
        dteGerberRelease.ReadOnly = Protected;
        chkLBLRequired.ReadOnly = Protected;
        chkBOMRequired.ReadOnly = Protected;
        //epiCheckBoxC22.Enabled = IsStatusNull;
        btnRequest.Enabled = IsStatusNull;
        // col 2
        dteOpen.Enabled = IsStatusNull;
        dteDue.Enabled = IsStatusNull;
        dteClosed.Enabled = IsStatusNull;
        dteOnHold.Enabled = IsStatusNull;
        dteOffHold.Enabled = IsStatusNull;
        dteWorkAreaRelease.Enabled = IsStatusNull;
        dteGerberRelease.Enabled = IsStatusNull;
        // desc
        //csm.GetNativeControlReference("368fd000-b055-4183-9d70-25d986650bd9").Enabled = true;
        //((EpiTextBox)csm.GetNativeControlReference("368fd000-b055-4183-9d70-25d986650bd9")).ReadOnly = Protected;
        edvUD100.dataView.Table.Columns["Character01"].ExtendedProperties["ReadOnly"] = Protected;
        // part tab
        btnPartNumber.Enabled = IsStatusNull;
        //txtPartDesc.Enabled = IsStatusNull;
        txtDWGCurrent.Enabled = IsStatusNull;
        txtDWGNew.Enabled = IsStatusNull;
        //txtProdGroup.Enabled = IsStatusNull;
        txtGPDCurrent.Enabled = IsStatusNull;
        txtGPDNew.Enabled = IsStatusNull;
        //txtPartClass.Enabled = IsStatusNull;
        txtGerberCurrent.Enabled = IsStatusNull;
        txtGerberNew.Enabled = IsStatusNull;
        chkLBLRequired.ReadOnly = Protected;
        chkBOMRequired.ReadOnly = Protected;
        chkLBLRequired.Enabled = IsStatusNull;
        chkBOMRequired.Enabled = IsStatusNull;
        csm.GetNativeControlReference("9ba33a90-56ec-4084-ae5d-f1f45a050f92").Enabled = IsStatusNull;
        //UD100Form.MainToolManager.Tools["EpiAddNewnewChild"].SharedProps.Enabled = IsStatusNull;
oTrans.PushStatusText("OpenAllFields END", false);
    }

    #region UI Event Handlers
    private void btnRequest_Click(object sender, EventArgs args) {
        // ** Place Event Handling Code Here **
        edvUD100.dataView[edvUD100.Row]["ShortChar02"] = "Request";
		edvUD100.dataView[edvUD100.Row]["date01"] = DateTime.Today.ToString("dd-MMM-yy");
        edvUD100.Notify(new EpiNotifyArgs(oTrans, edvUD100.Column, edvUD100.Row));
    }

    private void btnPrintReport_Click(object Sender, ToolClickEventArgs e) {
        if (edvUD100.Row < 0)
            return;

        LaunchFormOptions lfo = new LaunchFormOptions();
        lfo.ValueIn = edvUD100.dataView[edvUD100.Row]["Key1"].ToString();
        ProcessCaller.LaunchForm(oTrans, "UD2102", lfo);
    }

    private void key1TextBox_Leave(object sender, EventArgs e) {
        EpiTextBox key1TextBox = (EpiTextBox)csm.GetNativeControlReference("46567b2e-6bc0-4967-be35-a0ec6843838f");
        string key1String = key1TextBox.Text;
        string _ = string.Empty;
        oTrans.GetByID(key1String, _, _, _, _);
    }

    private void btnPartNumber_Click(object sender, EventArgs args) {
        bool isSelected;
        DataSet dataSet = SearchFunctions.listLookup(oTrans, "PartAdapter", out isSelected, true, string.Empty);
        if (!isSelected)
            return;

        EpiTextBox txtChildKey1 = (EpiTextBox)csm.GetNativeControlReference("34b47d57-c225-4900-8244-710d9f56651d");
        txtChildKey1.Text = dataSet.Tables[0].Rows[0]["PartNum"].ToString();
    }

    private void epiButtonC1_Click(object sender, EventArgs args) {
        List<string> addresses = GetSelectedUserEmailAddresses();
        string ECR_num = edvUD100.dataView[edvUD100.Row]["Key1"].ToString();
        string subject = String.Format("ECR {0} Updated", ECR_num);
        string body = String.Format("ECR {0} was updated.", ECR_num);
        SendEmail(addresses, subject, body);
    }

    private void SayElapsedTime(TimeSpan timespan) {
        string statusText = String.Format("Finished in {0:00}:{1:00}:{2:00}.{3:00}", timespan.Hours, timespan.Minutes, timespan.Seconds, timespan.Milliseconds / 10);
        oTrans.PushDisposableStatusText(statusText, true);
    }

    private void btnSelectUser_Click(object sender, EventArgs args) {
        // ** Place Event Handling Code Here **
        foreach (UltraGridRow row in eugAllUsers.Selected.Rows)
            selUsers.Add(row.Cells[0].Value.ToString());
        eugSelectedUsers.DataSource = selUsers;

        String catUsers = "";
        foreach (String user in selUsers)
            if (user.Length > 0)
                catUsers += user + "~";

        edvUD100.dataView[edvUD100.Row]["Character04"] = catUsers;
    }

    private void btnRemoveUser_Click(object sender, EventArgs args) {
        foreach (UltraGridRow row in eugSelectedUsers.Selected.Rows)
            selUsers.Remove(row.Cells[0].Value.ToString());

        String catUsers = "";
        foreach (String user in selUsers)
            if (user.Length > 0)
                catUsers += user + "~";

        edvUD100.dataView[edvUD100.Row]["Character04"] = catUsers;
        eugSelectedUsers.DataSource = selUsers;
    }
	private DataView affectedjobs;
	private DataTable dtaffectedjobs;
    private void btnRollup_Click(object sender, EventArgs args) {
        // Clear old values
        edvUD100.dataView[edvUD100.Row]["Character03"] = "";
        edvUD100.dataView[edvUD100.Row]["Character05"] = "";
        edvUD100.dataView[edvUD100.Row]["Character06"] = "";

        oTrans.PushStatusText("Gathering part where used...", true);
        newFindPartUsage();

        //  Roll up WHERE USED
		oTrans.PushStatusText("Roll Up Where Used", false);
        BOReader boReader = new BOReader(((Session)oTrans.Session).ConnectionPool);
        string fieldContents = string.Empty;
		foreach(DataRow t in whereused.Rows)
		{
			fieldContents += string.Format("{0} - {1}{2}", (string)t["Company"], (string)t["PartNum"], Environment.NewLine);
		}
        edvUD100.dataView[edvUD100.Row]["Character06"] = fieldContents;
        DynamicQueryAdapter dq1 = new DynamicQueryAdapter(oTrans);
		dq1.BOConnect();
        dq1.GetByID("CIC68322-PartSearch");
		Epicor.Mfg.BO.QueryExecutionDataSet ds1 = dq1.GetQueryExecutionParameters(dq1.QueryDesignData);
        oTrans.PushStatusText("Gathering part data...1", true);
		DataRow r = ds1.Tables["ExecutionParameter"].NewRow();
		r["ParameterName"] = "PartNum";
		r["ParameterValue"] = "";
		r["ValueType"] = "string";
		r["IsEmpty"] = false;
		r["RowIdent"] = string.Empty;
		r["RowMod"] = "A";
		ds1.Tables["ExecutionParameter"].Rows.Add(r);
        foreach (DataRow s in whereused.Rows) {
			oTrans.PushStatusText((string)s["PartNum"], false);
			ds1.Tables["ExecutionParameter"].Rows[0]["ParameterValue"] = (string)s["PartNum"];
			string resultFieldList = string.Empty;
			int topNRecords = 0;
			bool hasMoreRecords;
			dq1.ExecuteByIDParametrized("CIC68322-PartSearch", ds1, "", topNRecords, out hasMoreRecords);
			DataSet QueryResults = dq1.QueryResults;
	        Part part = new Part(((Session)oTrans.Session).ConnectionPool);
			string onHold = string.Empty;
	        foreach (DataRow row in QueryResults.Tables["Results"].Rows) {
            	onHold = row[0].ToString();
			}
            if (!String.IsNullOrEmpty(onHold))
                fieldContents += string.Format("{0} - {1}{2}", s, onHold, Environment.NewLine);
            else
                fieldContents += string.Format("{0}{1}", s, Environment.NewLine);
        }
		dq1.Dispose();
		dq1 = null;
//        edvUD100.dataView[edvUD100.Row]["Character06"] = String.Join(Environment.NewLine, whereUsed.ToArray());
		oTrans.PushStatusText("Roll up Affected WOs", false);
        //  Roll up AFFECTED WOs
        oTrans.PushStatusText("Finding affected WOs...", true);
        affectedWOs = new List<string>();
		string whereClause = string.Empty;
		if(affectedjobs == null){ // only run the query once.
			DynamicQueryAdapter dq = new DynamicQueryAdapter(this.oTrans);
			dq.BOConnect();
			string QueryID = "CIC68322-AffectedJobs";
			dq.ExecuteByID(QueryID);
			affectedjobs = new DataView(dq.QueryResults.Tables[0]);
			dq.Dispose();
			dq = null;
		}
        oTrans.PushStatusText("Finding JobHead.PartNum...", true);
		dtaffectedjobs = new DataTable();
		dtaffectedjobs.Columns.Add("Company", typeof(string));
		dtaffectedjobs.Columns.Add("JobNum", typeof(string));
		dtaffectedjobs.Columns.Add("StartDate", typeof(DateTime));
		dtaffectedjobs.Columns.Add("Qty", typeof(int));
        foreach (DataRow row in whereused.Rows) {
			string s = (string)row["PartNum"];
			whereClause = string.Format("JobHead.PartNum='{0}'", s);
			affectedjobs.RowFilter = whereClause;
            foreach (DataRowView dr in affectedjobs){
				DataRow newrow = dtaffectedjobs.NewRow();
        oTrans.PushStatusText(string.Format("Finding JobHead.PartNum...1"), true);
				newrow["Company"]= (string)dr[0];
        oTrans.PushStatusText(string.Format("Finding JobHead.PartNum...2"), true);
				newrow["JobNum"] = (string)dr[1];
        oTrans.PushStatusText(string.Format("Finding JobHead.PartNum...3"), true);
				try{
				newrow["StartDate"] = Convert.ToDateTime(dr[2]);
				}
				catch{}
        oTrans.PushStatusText(string.Format("Finding JobHead.PartNum...4"), true);
				newrow["Qty"] = Convert.ToInt32((decimal)dr[3]);
				dtaffectedjobs.Rows.Add(newrow);
//                affectedWOs.Add(String.Format("{0} - {1} - {2} - {3}", dr[0], dr[1], Convert.ToDateTime(dr[2]).ToString("dd-MMM-yy"), Convert.ToInt32(dr[3]).ToString("D3")));
			}
        }

		epiUltraGridC1_AffectedWorkorders.DataSource = dtaffectedjobs;

        fieldContents = "";
		foreach(DataRow t in dtaffectedjobs.Rows)
		{
			fieldContents += string.Format("{0} - {1} - {2} - {3}{4}", (string)t["Company"], (string)t["JobNum"], (DateTime)t["StartDate"], (int)t["Qty"], Environment.NewLine);
		}

        edvUD100.dataView[edvUD100.Row]["Character03"] = fieldContents;

        oTrans.PushStatusText("Finding Inventory...", true);
        // Find inventory
		//CIC68322-PartWhseSearch_ECR
        DynamicQueryAdapter dq2 = new DynamicQueryAdapter(oTrans);
		dq2.BOConnect();
        dq2.GetByID("CIC68322-PartWhseSearch_ECR");
		Epicor.Mfg.BO.QueryExecutionDataSet ds2 = dq2.GetQueryExecutionParameters(dq2.QueryDesignData);
        oTrans.PushStatusText("Gathering part data...1", true);
		DataRow r2 = ds2.Tables["ExecutionParameter"].NewRow();
		r2["ParameterName"] = "PartNum";
		r2["ParameterValue"] = "";
		r2["ValueType"] = "string";
		r2["IsEmpty"] = false;
		r2["RowIdent"] = string.Empty;
		r2["RowMod"] = "A";
		ds2.Tables["ExecutionParameter"].Rows.Add(r2);




        oTrans.PushStatusText("Finding usage...", true);

		DataTable dispositioninfo = new DataTable();
		dispositioninfo.Columns.Add("Company", typeof(string));
		dispositioninfo.Columns.Add("PartNum", typeof(string));
		dispositioninfo.Columns.Add("Warehouse", typeof(string));
		dispositioninfo.Columns.Add("On Hand Qty", typeof(decimal));
		dispositioninfo.Columns.Add("Plant", typeof(string));
        foreach (DataRow partrow in whereused.Rows) {
			ds2.Tables["ExecutionParameter"].Rows[0]["ParameterValue"] = (string)partrow["PartNum"];
			int topNRecords = 0;
			bool hasMoreRecords;
			dq2.ExecuteByIDParametrized("CIC68322-PartWhseSearch_ECR", ds2, "", topNRecords, out hasMoreRecords);
	        foreach (DataRow row in dq2.QueryResults.Tables["Results"].Rows) {
	            if (Convert.ToDecimal(row[3]) != 0)
				{
					DataRow newrow = dispositioninfo.NewRow();
					newrow["Company"] = (string)row[0];
					newrow["PartNum"] = (string)row[1];
					newrow["Warehouse"] = (string)row[2];
					newrow["On Hand Qty"] = Convert.ToDecimal(row[3]);
					newrow["Plant"] = row[4].ToString();
					dispositioninfo.Rows.Add(newrow);
				}
			}
        }

		DataView dv = new DataView(dispositioninfo);
		dv.Sort = "Company, PartNum, Warehouse, On Hand Qty, Plant";
		dispositioninfo = dv.ToTable(true, "Company", "PartNum", "Warehouse", "On Hand Qty", "Plant");

		epiUltraGridC1_DispositionInfo.DataSource = dispositioninfo;
		dq2.Dispose();

        fieldContents = "";
		foreach(DataRow t in dispositioninfo.Rows)
		{
			fieldContents += string.Format("{0} - {1} - {2} - {3} - {4}{5}", (string)t["Company"], (string)t["PartNum"], (string)t["Warehouse"], (decimal)t["On Hand Qty"], (string)t["Plant"], Environment.NewLine);
		}

        edvUD100.dataView[edvUD100.Row]["Character05"] = fieldContents;

        oTrans.PushStatusText("Ready.", false);
    }
    #endregion

    #region Email functionality
    private void SendStatusAlerts(string status, string ECRNum) {
oTrans.PushStatusText("SendStatusAlerts", false);
        string subject = string.Format("ECR: {0} Status Changed to {1}", ECRNum, status);
        string body = string.Format("ECR: {0} Status Changed to {1}", ECRNum, status);
        Stopwatch stopwatch = Stopwatch.StartNew();
        switch (status) {
            case "Request": {
                oTrans.PushDisposableStatusText("Emailing ECR managers...", true);
                List<string> addresses = GetECRManagerEmailAddresses();
                SendEmail(addresses, subject, body);
            }
                break;
            case "Pending Acknowledgment": {
                oTrans.PushDisposableStatusText("Emailing associated users...", true);
                List<string> addresses = GetSelectedUserEmailAddresses();
                SendEmail(addresses, subject, body);
            }
                break;
            case "Open": {
                oTrans.PushDisposableStatusText("Emailing team lead...", true);
				//List<string> addresses = GetTeamLeadEmailAddresses();
				 List<string> addresses = GetSelectedUserEmailAddresses();
                SendEmail(addresses, subject, body);
            }
                break;
            case "Pending Approval": {
                oTrans.PushDisposableStatusText("Emailing associated users...", true);
                List<string> addresses = GetSelectedUserEmailAddresses();
                SendEmail(addresses, subject, body);
            }
                break;
            case "Closed": {}
                break;
            case "Rejected": {}
                break;
        }
        SayElapsedTime(stopwatch.Elapsed);
oTrans.PushStatusText("SendStatusAlerts end", false);
    }

    private DataTable GetUserFileRows() {
        DynamicQuery dq = new DynamicQuery(((Session)oTrans.Session).ConnectionPool);
        QueryDesignDataSet qdds = dq.GetByID("CIC68322-GetEmailAddress");

        oTrans.PushDisposableStatusText("Starting...", true);
        Stopwatch stopwatch = Stopwatch.StartNew();
        DataSet ds = dq.Execute(qdds);
        SayElapsedTime(stopwatch.Elapsed);

        foreach (DataColumn col in ds.Tables[0].Columns) {
            col.ReadOnly = true;
            for (int i = 0; i < qdds.QueryField.Count; i++)
                if (col.Caption.Contains(".") && col.Caption.Split('.')[1] == qdds.QueryField[i].FieldName) {
                    col.Caption = qdds.QueryField[i].FieldLabel;
                    break;
                }
        }

        return ds.Tables[0];
    }

    private List<string> GetTeamLeadEmailAddresses() {
        string Team = edvUD100.dataView[edvUD100.Row]["Character02"].ToString();
        string TeamID = string.Empty;
        switch (Team) {
            case "Team Black": {
                TeamID = "TM_Black";
            }
                break;
            case "Team Blue": {
                TeamID = "TM_Blue";
            }
                break;
            case "Team Flex": {
                TeamID = "TM_Flex";
            }
                break;
            case "Team Green": {
                TeamID = "TM_Green";
            }
                break;
            case "Team Red": {
                TeamID = "TM_Red";
            }
                break;
            case "Team TCI": {
                TeamID = "TM_CI";
            }
                break;
            case "Team R&D": {
                TeamID = "TM_RD";
            }
                break;
            case "Team Yellow": {
                TeamID = "TM_Yello";
            }
                break;
            case "Team UK": {
                TeamID = "TM_UK";
            }
                break;
        }

        DataTable userFileRows = GetUserFileRows();

        List<string> addresses = new List<string>();
        foreach (DataRow row in userFileRows.Rows) {
            string emailAddress = row[0].ToString();
            string username = row[1].ToString();
            string groupList = row[2].ToString();
            if (!string.IsNullOrEmpty(emailAddress) && groupList.Contains(TeamID))
                addresses.Add(emailAddress);
        }
        return addresses;
    }

    private List<string> GetECRManagerEmailAddresses() {
        DataTable userFileRows = GetUserFileRows();

        List<string> addresses = new List<string>();
        foreach (DataRow row in userFileRows.Rows) {
            string emailAddress = row[0].ToString();
            string username = row[1].ToString();
            string groupList = row[2].ToString();
            if (!string.IsNullOrEmpty(emailAddress) && groupList.Contains("ECR1"))
                addresses.Add(emailAddress);
        }
        return addresses;
    }

    private List<string> GetSelectedUserEmailAddresses() {
        List<string> usernames = new List<string>();
        foreach (UltraGridRow row in eugSelectedUsers.Rows) {
            string username = row.Cells["Value"].Value.ToString();
            usernames.Add(username);
        }
        List<string> addresses = GetEmailAddresses(usernames);
        return addresses;
    }

    private List<string> GetEmailAddresses(List<string> usernames) {
        DataTable userFileRows = GetUserFileRows();

        List<string> addresses = new List<string>();
        foreach (DataRow row in userFileRows.Rows) {
            string emailAddress = row[0].ToString();
            string username = row[1].ToString();
            if (!string.IsNullOrEmpty(emailAddress) && usernames.Contains(username))
                addresses.Add(emailAddress);
        }
        return addresses;
    }

    private void SendEmail(List<string> addresses, string subject, string body) {
        BOReader reader = new BOReader(((Session)oTrans.Session).ConnectionPool);
        DataSet smtpDataSet = reader.GetRows("Company", string.Format("Company='{0}'", ((Session)oTrans.Session).CompanyID), "SMTPServer,SMTPPort,EmailFromAddr");

        MailMessage message = new MailMessage();
        message.From = new MailAddress(smtpDataSet.Tables[0].Rows[0][2].ToString());
        message.Subject = subject;
        message.Body = body;

        if (edvUD100.dataView[edvUD100.Row]["ShortChar01"].ToString() == "AS9100 DOC Change")
            message.To.Add("AS9100Update@franklinproducts.net");
        else
            foreach (string a in addresses)
                message.To.Add(a);

        string smtpHost = smtpDataSet.Tables[0].Rows[0][0].ToString();
        int smtpPort = Convert.ToInt32(smtpDataSet.Tables[0].Rows[0][1]);
        SmtpClient smtp = new SmtpClient(smtpHost, smtpPort);
        smtp.Send(message);
    }
    #endregion

    #region LookUp Tab
    private void btnFetchAll_Click(object sender, EventArgs args) {
        //  Find all parts containing ECR parts
        List<string> AffectedParts = FindPartUsage();

        //  Get data
        DataTable usage = new DataTable();
        DynamicQuery dq = new DynamicQuery(((Session)oTrans.Session).ConnectionPool);
        QueryDesignDataSet qdds = dq.GetByID("CIC68322-ECRWhereUsed");

        foreach (string s in AffectedParts) {
            oTrans.PushDisposableStatusText(string.Format("Finding usage for part: {0}...", s), true);
            foreach (QueryDesignDataSet.QueryWhereItemRow qwi in qdds.QueryWhereItem.Rows)
                if (qwi.FieldName == "PartNum")
                    qwi.RValue = s;

            DataTable queryResults = dq.Execute(qdds).Tables[0];

            if (usage.Rows.Count < 1)
                usage = queryResults.Copy();
            else
                foreach (DataRow row in queryResults.Rows)
                    usage.ImportRow(row);
        }

        oTrans.PushDisposableStatusText("Summarizing data...", true);

        //  SOs
        eugSO.DataSource = SummarizeFieldForFetchAll(usage, "OrderDtl.OrderNum");
        //  POs
        eugPO.DataSource = SummarizeFieldForFetchAll(usage, "PODetail.PONUM");
        //  TOs
        eugTO.DataSource = SummarizeFieldForFetchAll(usage, "TFOrdDtl.TFOrdNum");
        //  Jobs        
        eugJob.DataSource = SummarizeFieldForFetchAll(usage, "JobHead.JobNum");

        oTrans.PushDisposableStatusText("Ready.", true);
    }

    private string[] SummarizeFieldForFetchAll(DataTable SrcTable, string Field) {
        List<string> items = new List<string>();

        foreach (DataRow dr in SrcTable.Rows)
            if (!String.IsNullOrEmpty(dr[Field].ToString()) && !items.Contains(dr[Field].ToString()))
                items.Add(dr[Field].ToString());
        return items.ToArray();
    }
    #endregion

    #region Checkbox Functions
    private bool IsAcknowledged(DataColumnChangeEventArgs args) {
		oTrans.PushStatusText("IsAcknowledged", false);
        //  Cross reference ack field to app fields
        Dictionary<string, string> FieldRef = new Dictionary<string, string>();
		oTrans.PushStatusText("IsAcknowledged 1", false);
        FieldRef.Add("CertificationAppCheckbox", "CertificationAckCheckbox");
		oTrans.PushStatusText("IsAcknowledged 2", false);
        FieldRef.Add("ContractsAppCheckbox", "ContractsAckCheckbox");
		oTrans.PushStatusText("IsAcknowledged 3", false);
        FieldRef.Add("DesignEngAppCheckbox", "DesignEngAckCheckbox");
		oTrans.PushStatusText("IsAcknowledged 4", false);
        FieldRef.Add("MangEngAppCheckbox", "MangEngAckCheckbox");
		oTrans.PushStatusText("IsAcknowledged 5", false);
        FieldRef.Add("ProductionControlAppCheckbox", "ProductionControlAckCheckbox");
		oTrans.PushStatusText("IsAcknowledged 6", false);
        FieldRef.Add("QualityAppCheckbox", "QualityAckCheckbox");
		oTrans.PushStatusText("IsAcknowledged 7", false);
        FieldRef.Add("AS9100_AppCheckBox", "AS9100_AckCheckBox"); //added by Scott
		oTrans.PushStatusText("IsAcknowledged 8", false);
        FieldRef.Add("SCM_AppCheckbox", "SCM_AckCheckbox"); //added by Scott
		oTrans.PushStatusText("IsAcknowledged 9", false);
		FieldRef.Add("SCM_2_AppCheckbox", "SCM_2_AckCheckbox"); //added by Scott
		oTrans.PushStatusText("IsAcknowledged 10", false);
		
        //bool Ack = Convert.ToBoolean(edvUD100.dataView[edvUD100.Row][FieldRef[args.Column.ColumnName]]);
        bool Ack = Convert.ToBoolean(args.ProposedValue);
		oTrans.PushStatusText("IsAcknowledged END", false);
        return Ack;
    }

    private void SetCheckBoxNotes(DataColumnChangeEventArgs args) {
oTrans.PushStatusText("SetCheckBoxNotes", false);
        //  Store relationship between check boxes and note fields
        Dictionary<string, string> FieldRef = new Dictionary<string, string>();
        FieldRef.Add("CertificationAckCheckbox", "CertificationAckNotes");
        FieldRef.Add("CertificationAppCheckbox", "CertificationAppNotes");
        FieldRef.Add("ContractsAckCheckbox", "ContractsAckNotes");
        FieldRef.Add("ContractsAppCheckbox", "ContractsAppNotes");
        FieldRef.Add("DesignEngAckCheckbox", "DesignEngAckNotes");
        FieldRef.Add("DesignEngAppCheckbox", "DesignEngAppNotes");
        FieldRef.Add("MangEngAckCheckbox", "MangEngAckNotes");
        FieldRef.Add("MangEngAppCheckbox", "MangengAppNotes");
        FieldRef.Add("ProductionControlAckCheckbox", "ProductionControlAckNotes");
        FieldRef.Add("ProductionControlAppCheckbox", "ProductionControlAppNotes");
        FieldRef.Add("QualityAckCheckbox", "QualityAckNotes");
        FieldRef.Add("QualityAppCheckbox", "QualityAppNotes");
        FieldRef.Add("AS9100_AckCheckBox", "AS9100_AckNotes"); //added by Scott
        FieldRef.Add("AS9100_AppCheckBox", "AS9100AppNotes"); //added by Scott
        FieldRef.Add("SCM_AckCheckbox", "SCM_AckNotes"); //added by Scott
        FieldRef.Add("SCM_AppCheckbox", "SCM_AppNotes"); //added by Scott
        FieldRef.Add("SCM_2_AckCheckbox", "SCM_2_AckNotes"); //added by Scott
        FieldRef.Add("SCM_2_AppCheckbox", "SCM_2_AppNotes"); //added by Scott
        FieldRef.Add("CheckBox01", "Tasks_PatternNotes");
        FieldRef.Add("CheckBox02", "Tasks_GPDNotes");
        FieldRef.Add("CheckBox03", "Tasks_LabelNotes");
        FieldRef.Add("CheckBox04", "Tasks_DrawingNotes");
        FieldRef.Add("CheckBox05", "Tasks_BOMNotes");
        FieldRef.Add("CheckBox06", "Tasks_PricingNotes");
        FieldRef.Add("CheckBox07", "Tasks_CustomerApproval");
        FieldRef.Add("CheckBox08", "Tasks_CustomerSourceNotes");
        FieldRef.Add("CheckBox09", "Tasks_DispositionNotes");
        FieldRef.Add("CheckBox10", "Tasks_ToolingNotes");
        FieldRef.Add("CheckBox11", "Tasks_RawMaterialNotes");
        FieldRef.Add("CheckBox12", "Tasks_InterPlantNotes");
        FieldRef.Add("CheckBox13", "Tasks_FAINotes");
        FieldRef.Add("CheckBox14", "Tasks_CertificationNotes");
        FieldRef.Add("CheckBox16", "Appr_CTNotes");
        FieldRef.Add("CheckBox17", "Appr_TXNotes");
        FieldRef.Add("CheckBox18", "Appr_MXNotes");
        FieldRef.Add("CheckBox19", "Appr_UKNotes");
        FieldRef.Add("CheckBox20", "Appr_PLNotes"); //added by Scott
		FieldRef.Add("Tasks_PartDescBOOL", "Tasks_PartDesc"); //added by Scott
		FieldRef.Add("Tasks_SubmitBOOL", "Tasks_SubmitToCust"); //added by Scott
		FieldRef.Add("Tasks_GerberReadyBool", "Tasks_GerberReady"); //added by Scott
		FieldRef.Add("Tasks_GerberReleaseBool", "Tasks_GerberRelease"); //added by Scott
		FieldRef.Add( "SCD_ENG_YN","SCD_ENG_TSK"); //added by Scott
		

        string ColumnName = args.Column.ColumnName;
        bool ProposedValue = Convert.ToBoolean(args.ProposedValue);
        if (ProposedValue && edvUD100.dataView[edvUD100.Row][FieldRef[ColumnName]].ToString() == "")
            edvUD100.dataView[edvUD100.Row][FieldRef[ColumnName]] = string.Format("{0}-{1}-{2} ", ((Session)oTrans.Session).UserID, DateTime.Now.ToShortTimeString(), DateTime.Today.ToString("dd-MMM-yy"));
        else if (!ProposedValue)
            edvUD100.dataView[edvUD100.Row][FieldRef[ColumnName]] = "";
oTrans.PushStatusText("SetCheckBoxNotes END", false);
    }
    #endregion
	private DataTable whereused;
    private List<string> FindPartUsage() {
        // Find all parts containing ECR parts.
        oTrans.PushStatusText("Gathering part where used...", true);
        List<string> whereUsed = new List<string>();
        DynamicQuery dq = new DynamicQuery(((Session)oTrans.Session).ConnectionPool);
        QueryDesignDataSet qdds = dq.GetByID("CIC68322-ECRRollup");
        qdds.QueryWhereItem[0].RValue = edvUD100.dataView[edvUD100.Row]["Key1"].ToString();
        DataSet ds = dq.Execute(qdds);

        Part part = new Part(((Session)oTrans.Session).ConnectionPool);
        foreach (DataRow row in ds.Tables[0].Rows) {
            string childPart = row[0].ToString();
            if (!part.PartExists(childPart))
                continue;
            whereUsed.Add(childPart);
            for (int i = 1; i <= 5; i++) {
                string parentPart = row[i].ToString();
                if (!String.IsNullOrEmpty(parentPart))
                    whereUsed.Add(parentPart);
            }
        }

        oTrans.PushStatusText("Deduping list...", true);
        whereUsed = RemoveDuplicates(whereUsed);
        oTrans.PushStatusText("Processing...", true);
        whereUsed.Sort();
        return whereUsed;
    }

    private void newFindPartUsage() {
		whereused = new DataTable();
		whereused.Columns.Add("Company", typeof(string));
		whereused.Columns.Add("PartNum", typeof(string));
        // Find all parts containing ECR parts.
        oTrans.PushStatusText("Gathering part where used...", true);
        List<string> whereUsed = new List<string>();
        DynamicQueryAdapter dq = new DynamicQueryAdapter(oTrans);
		dq.BOConnect();
        dq.GetByID("CIC68322-ECRRollupIndividual");
		Epicor.Mfg.BO.QueryExecutionDataSet ds = dq.GetQueryExecutionParameters(dq.QueryDesignData);
        oTrans.PushStatusText("Gathering part where used...1", true);
		DataRow r = ds.Tables["ExecutionParameter"].NewRow();
		r["ParameterName"] = "PartNum";
		r["ParameterValue"] = string.Empty;
		r["ValueType"] = "string";
		r["IsEmpty"] = false;
		r["RowIdent"] = string.Empty;
		r["RowMod"] = "A";
		ds.Tables["ExecutionParameter"].Rows.Add(r);
		string resultFieldList = string.Empty;
		int topNRecords = 0;
		bool hasMoreRecords;

        DynamicQueryAdapter partsearch = new DynamicQueryAdapter(oTrans);
		partsearch.BOConnect();
        partsearch.GetByID("CIC68322-PartSearch");
		Epicor.Mfg.BO.QueryExecutionDataSet ds_partsearch = partsearch.GetQueryExecutionParameters(partsearch.QueryDesignData);
        oTrans.PushStatusText("Gathering part data...1", true);
		DataRow r_partsearch = ds_partsearch.Tables["ExecutionParameter"].NewRow();
		r_partsearch["ParameterName"] = "PartNum";
		r_partsearch["ParameterValue"] = "";
		r_partsearch["ValueType"] = "string";
		r_partsearch["IsEmpty"] = false;
		r_partsearch["RowIdent"] = string.Empty;
		r_partsearch["RowMod"] = "A";
		ds_partsearch.Tables["ExecutionParameter"].Rows.Add(r_partsearch);

		foreach(DataRowView DRV in edvUD100A.dataView)
		{
			ds_partsearch.Tables["ExecutionParameter"].Rows[0]["ParameterValue"] = (string)DRV["ChildKey1"];
			partsearch.ExecuteByIDParametrized("CIC68322-PartSearch", ds_partsearch, "", topNRecords, out hasMoreRecords);
			foreach(DataRow row in partsearch.QueryResults.Tables["Results"].Rows){
						DataRow childnewrow = whereused.NewRow();
						childnewrow["Company"] = (string)row[3];
						childnewrow["PartNum"] = (string)row[2];
						whereused.Rows.Add(childnewrow);
			}


			ds.Tables["ExecutionParameter"].Rows[0]["ParameterValue"] = (string)DRV["ChildKey1"];
			dq.ExecuteByIDParametrized("CIC68322-ECRRollupIndividual", ds, "", topNRecords, out hasMoreRecords);
	        oTrans.PushStatusText("Gathering part where used...2", true);
			DataSet QueryResults = dq.QueryResults;
	        oTrans.PushStatusText(string.Format("Gathering part where used...3({0})",QueryResults.Tables["Results"].Rows.Count), true);
	        foreach (DataRow row in QueryResults.Tables["Results"].Rows) {
	            for (int i = 0; i <= 5; i++) {
					if(!String.IsNullOrEmpty(row[i].ToString()) && !String.IsNullOrEmpty(row[5 + i].ToString())){
						DataRow childnewrow = whereused.NewRow();
						childnewrow["Company"] = (string)row[5+i];
						childnewrow["PartNum"] = (string)row[i];
						whereused.Rows.Add(childnewrow);
					}
	            }
	        }
		}
		oTrans.PushStatusText("Getting distinct and ordering...", false);
		DataView dv = new DataView(whereused);
		dv.Sort = "Company, PartNum";
		whereused = dv.ToTable(true, "Company", "PartNum");
		epiUltraGridC1_WhereUsed.DataSource = whereused;
		dq.Dispose();
		dq = null;
		partsearch.Dispose();
		partsearch = null;
    }

    private List<string> RemoveDuplicates(List<string> lines) {
        Dictionary<string, bool> distinct = new Dictionary<string, bool>();
        foreach (string line in lines)
            distinct[line] = true; // true or false (we're only interested in the Keys, anyway).
        return new List<string>(distinct.Keys);
    }

    private void Debug(string s) {
        MessageBox.Show(s);
    }

	private void edvUD100A_EpiViewNotification(EpiDataView view, EpiNotifyArgs args)
	{
		// ** Argument Properties and Uses **
		// view.dataView[args.Row]["FieldName"]
		// args.Row, args.Column, args.Sender, args.NotifyType
		// NotifyType.Initialize, NotifyType.AddRow, NotifyType.DeleteRow, NotifyType.InitLastView, NotifyType.InitAndResetTreeNodes
		if ((args.NotifyType == EpiTransaction.NotifyType.AddRow))
		{
			if ((args.Row > -1))
			{
			}
		}
	}
}
